#Welcome to Numpy tutorial 

In [1]:
import numpy as np

In [2]:
myarr =np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0,1]

np.int64(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]=45

In [7]:
myarr

array([[ 3, 45, 32,  7]])

# Array creation : Conversion from other Python Structures

In [8]:
listarray = np.array([[1,2,3], [5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,34,44})

array({34, 44}, dtype=object)

In [14]:
zeros=np.zeros((2, 5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
b=np.arange(20,60)

In [17]:
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

In [18]:
c=np.arange(15)

In [19]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,50,10)

In [21]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [22]:
emp = np.empty((40,60))

In [23]:
emp

array([[7.88275970e-312, 7.88274049e-312, 0.00000000e+000, ...,
        7.88273952e-312, 7.88273952e-312, 7.88273952e-312],
       [1.27319747e-313, 4.88059032e-313, 2.96439388e-323, ...,
        7.88273953e-312, 9.88131292e-323, 6.95241178e-310],
       [0.00000000e+000, 0.00000000e+000, 3.39519327e-313, ...,
        7.88273953e-312, 5.61752639e-321, 7.88273953e-312],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],
      shape=(40, 60))

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
ide=np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr= arr.ravel()

In [33]:
arr.shape

(99,)

In [43]:
e = [[1,2,3],[4,5,6],[7,1,0]]

In [46]:
op = np.array(e)

In [47]:
op

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
op.sum(axis=0)

array([12,  8,  9])

In [49]:
op.sum(axis=1)

array([ 6, 15,  8])

In [50]:
op.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
op.flat

In [52]:
for item in op.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
op.ndim

2

In [55]:
op.nbytes

72

In [56]:
one = np.array([1,3,4,56,4])

In [57]:
one.argmax()

np.int64(3)

In [58]:
one.argmin()

np.int64(0)

In [59]:
one.argsort()

array([0, 1, 2, 4, 3])

In [60]:
op.argmin()

np.int64(8)

In [61]:
op.argmax()

np.int64(6)

In [62]:
op.argmax(axis=0)

array([2, 1, 1])

In [63]:
op.argmax(axis=1)

array([2, 2, 0])

In [64]:
op.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [65]:
op.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [66]:
op.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [72]:
op.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [76]:
op2= np.array([[1,2,1],
               [4,0,6],
               [15,2,0]])

In [77]:
op+op2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [22,  3,  0]])

In [78]:
op                            

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
op2

array([[ 1,  2,  1],
       [ 4,  0,  6],
       [15,  2,  0]])

In [80]:
op*op2

array([[  1,   4,   3],
       [ 16,   0,  36],
       [105,   2,   0]])

In [81]:
np.sqrt(op2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [3.87298335, 1.41421356, 0.        ]])

In [82]:
op.sum()

np.int64(29)

In [86]:
(np.where(op>5))

(array([1, 2]), array([2, 0]))

In [87]:
type(np.where(op>5))

tuple

In [88]:
np.count_nonzero(op)

8

In [90]:
np.nonzero(op)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [91]:
import sys

In [102]:
py_ar=[0,4,55,2]

In [103]:
np_ar = np.array(py_ar)

In [104]:
sys.getsizeof(1) * len(py_ar)

112

In [105]:
np_ar.itemsize * np_ar.size

32