In [1]:
import numpy as np

**Create a Numpy array with values ranging from 1 to 20.**

In [2]:
a=np.arange(1,21)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Create a 5x5 array filled with random integers between 10 and 50**

In [4]:
b=np.random.randint(10,50,(5,5))

In [5]:
b

array([[35, 17, 27, 27, 37],
       [25, 39, 28, 22, 18],
       [38, 17, 26, 17, 22],
       [21, 47, 16, 18, 46],
       [10, 37, 20, 49, 27]], dtype=int32)

**Check the shape,size and datatype of a Numpy array.**

In [6]:
b.shape

(5, 5)

In [7]:
a.shape

(20,)

In [8]:
b.size

25

In [9]:
a.size

20

In [10]:
b.dtype

dtype('int32')

In [11]:
a.dtype

dtype('int64')

**Create an array of 10 evenly spaced values between 0 and 100.**

In [30]:
c=np.linspace(0,100,11,dtype=int)

In [31]:
c

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**Generate a 3x3 identity matrix using Numpy**

In [36]:
d=np.identity(3)

In [37]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Extract all even numbers from a given Numpy array.**

In [38]:
d[d%2==0]

array([0., 0., 0., 0., 0., 0.])

In [39]:
c[c%2==0]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [40]:
b[b%2==0]

array([28, 22, 18, 38, 26, 22, 16, 18, 46, 10, 20], dtype=int32)

**Retrieve the second row and  third column of a 3x3 matrix.**

In [41]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
e[1]

array([4, 5, 6])

In [55]:
e[:,2]

array([3, 6, 9])

**Reverse the element of a Numpy array**

In [56]:
e.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Convert a 1D array of size 12 into a 3x4 matrix.**

In [60]:
f=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [61]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
f.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Flatten 2D matrix into a 1D array**

In [63]:
g=np.array([[2,3,4],[5,6,7]])

In [64]:
g

array([[2, 3, 4],
       [5, 6, 7]])

In [67]:
g.flat

In [68]:
for i in g.flat:
    print(i)

2
3
4
5
6
7


In [69]:
g.reshape(6,1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

**Compute the square of each element in an array.**

In [72]:
g*g

array([[ 4,  9, 16],
       [25, 36, 49]])

In [73]:
f*f

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

**Find the mean,median, and standard deviation of an array.**

In [74]:
np.mean(g)

np.float64(4.5)

In [75]:
np.median(g)

np.float64(4.5)

In [77]:
np.std(g)

np.float64(1.707825127659933)

In [78]:
np.mean(f)

np.float64(6.5)

In [79]:
np.median(f)

np.float64(6.5)

In [80]:
np.std(f)

np.float64(3.452052529534663)

**Compute the cumulative sum of an array.**

In [81]:
np.cumsum(g)

array([ 2,  5,  9, 14, 20, 27])

In [82]:
np.cumsum(f)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

**Normalize an array so that its values range between 0 and 1.**

In [83]:
h=(g-np.min(g)) / (np.max(g)-np.min(g))

In [84]:
h

array([[0. , 0.2, 0.4],
       [0.6, 0.8, 1. ]])

**Find the Determinant of a square martrix.**

In [89]:
i=np.array([[1, 2], [3, 4]])

In [90]:
np.linalg.det(i)

np.float64(-2.0000000000000004)

**Replace all negative values in an array with zero.**

In [115]:
x1=np.array([[-2,-3,2],[-9,5,6],[-6,4,3]])

In [116]:
x1

array([[-2, -3,  2],
       [-9,  5,  6],
       [-6,  4,  3]])

In [119]:
x1[x1<0]=0
print(x1)

[[0 0 2]
 [0 5 6]
 [0 4 3]]


**Extract all elements greater than 50 from an array.**

In [120]:
f1=np.array([[45,67,87],[90,87,54],[35,65,43]])

In [121]:
f1

array([[45, 67, 87],
       [90, 87, 54],
       [35, 65, 43]])

In [124]:
f1[f1>50]

array([67, 87, 90, 87, 54, 65])

**Check if any elements in an array is greater than a given value.**

In [125]:
value=20

In [130]:
np.any(f1<value)

np.False_

In [131]:
np.any(f1>value)

np.True_

**Replace all values divisble by 3 in an array with -1.**

In [133]:
f1[f1%3==0]=-1
print(f1)

[[-1 67 -1]
 [-1 -1 -1]
 [35 65 43]]


**Count the number of occurence of each unique value in an array.**

In [136]:
d3=np.array([1,2,2,3,3,3,4,4,4,1,1,2,2,2,2,5,5,6,6,7,8,8,8,9])

In [137]:
d3

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 1, 1, 2, 2, 2, 2, 5, 5, 6, 6, 7, 8, 8,
       8, 9])

In [143]:
np.unique(d3, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([3, 6, 3, 3, 2, 2, 1, 3, 1]))