In [1]:
import numpy as np

**create a 1D array with values from 1 to 10.**

In [2]:
a=np.arange(11)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
b=np.arange(1,11)

In [5]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Create a 2D Numpy array (3x3) filled with zeros**

In [6]:
c=np.zeros([3,3])

In [7]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Create a Numpy array of 5 filled with ones**

In [8]:
d=np.ones([5])

In [9]:
d

array([1., 1., 1., 1., 1.])

**Generate an array with values ranging from 10 to 50.**

In [10]:
e=np.arange(10,51)

In [11]:
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an Array of 10 random numbers between 0 and 1**

In [12]:
f=np.linspace(0,1,10)

In [13]:
f

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Extract the first three elements from numpy array**

In [14]:
g=f[:3]

In [15]:
g

array([0.        , 0.11111111, 0.22222222])

In [16]:
g1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
g1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Retrieve the Last 2 Rows of 3x3 matrix**

In [18]:
h=g1[1:]

In [19]:
h

array([[4, 5, 6],
       [7, 8, 9]])

**Reverse a numpy array**

In [20]:
h.T

array([[4, 7],
       [5, 8],
       [6, 9]])

In [21]:
g1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Get every second element from an array**

In [22]:
i=g1[0,1]

In [23]:
i

np.int64(2)

In [24]:
j=h[0,1],g1[0,2]

In [31]:
j

(np.int64(5), np.int64(3))

**Reshape a 1D array of Size 9 into 3x3**

In [39]:
k=np.arange(1,10)

In [40]:
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
j1=k.reshape(3,3)

In [47]:
j1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Flatten a 2D array into a 1D array**

In [53]:
j1.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

**Stack two Numpy arrays vertically and horizontally**

In [54]:
np.vstack((g1,j1))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.hstack((g1,j1))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

**Add,Subtract,Multiply and Divide two Numpy arrays**

In [65]:
arr1=np.arange(10,19)

In [67]:
arr1.reshape(3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
arr2=np.arange(20,29)

In [70]:
arr2.reshape(3,3)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [77]:
np.add(arr1, arr2).reshape(3,3)

array([[30, 32, 34],
       [36, 38, 40],
       [42, 44, 46]])

In [108]:
w1=np.subtract(arr1, arr2).reshape(3,3)

In [109]:
w1

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [79]:
np.multiply(arr1, arr2).reshape(3,3)

array([[200, 231, 264],
       [299, 336, 375],
       [416, 459, 504]])

In [80]:
np.divide(arr1, arr2).reshape(3,3)

array([[0.5       , 0.52380952, 0.54545455],
       [0.56521739, 0.58333333, 0.6       ],
       [0.61538462, 0.62962963, 0.64285714]])

**Find the maximum, minimum, and mean values of an array.**

In [81]:
np.max(arr1)

np.int64(18)

In [82]:
np.min(arr1)

np.int64(10)

In [83]:
np.mean(arr1)

np.float64(14.0)

In [84]:
np.mean(arr2)

np.float64(24.0)

**Compute the sum of all elements in an array.**

In [85]:
np.sum(arr1)

np.int64(126)

**Find the square root and exponential of each element in an array.**

In [90]:
np.sqrt(arr1)

array([3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069])

In [91]:
np.sqrt(arr2)

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262])

In [97]:
np.exp(arr1)

array([2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07])

In [98]:
np.exp(arr2)

array([4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12])

**Find all even numbers in a NumPy array.**

In [100]:
a1=np.array([[2,4,6],[3,5,7],[1,3,9]])

In [101]:
a1

array([[2, 4, 6],
       [3, 5, 7],
       [1, 3, 9]])

In [103]:
a2=a1[a1%2==0]

In [104]:
a2

array([2, 4, 6])

**For Odd Number**

In [105]:
a3=a1[a1%2==1]

In [107]:
a3

array([3, 5, 7, 1, 3, 9])

**Replace all negative numbers in an array with zero.**

In [125]:
a4=np.array([[2,-3,-5],[-9,7,3],[-3,4,5]])

In [126]:
a4

array([[ 2, -3, -5],
       [-9,  7,  3],
       [-3,  4,  5]])

In [127]:
a4[a4<0]=0

In [128]:
a4

array([[2, 0, 0],
       [0, 7, 3],
       [0, 4, 5]])

**Extract all numbers greater than 10 from an array**

In [129]:
b2=np.array([[1,9,12],[23,44,8],[34,56,54]])

In [130]:
b2

array([[ 1,  9, 12],
       [23, 44,  8],
       [34, 56, 54]])

In [131]:
b2[b2>10]

array([12, 23, 44, 34, 56, 54])

**Create a NumPy identity matrix of size 4x4.**

In [139]:
c2=np.identity(4)

In [140]:
c2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Generate a NumPy array of 20 random integers between 1 and 100 and sort them.**

In [154]:
d1=np.linspace(1,100,20,dtype=int)

In [155]:
d1

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100])

**Find the dot product of two matrices.**

In [159]:
np.dot(b2,2)

array([[  2,  18,  24],
       [ 46,  88,  16],
       [ 68, 112, 108]])

In [161]:
l1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [162]:
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
l2=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [164]:
l2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [165]:
np.dot(l1,l2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])